---
title: "Supplementary - TreeAllometries"
author: ''
date: "5 Aug 2014"
output: html_document
---

# Preparing workspace

```{r message =FALSE}
rm(list=ls(all=TRUE))
source("01-packages.R", print.eval =F)
load(file = "../data/cleanedData.RData")
stagesPerPlot <- as.factor(c("Establishment", "Establishment", "Establishment", "Exclusion", "Exclusion","Exclusion", "Old-growth", "Old-growth"))
attach(cleanedData)

colorMap <- function(value){
  colors = c("black", "chartreuse4", "darkorange")
  #colors = c("black", "darkgrey", "lightgrey")
  return(colors[value])
}
```


### Session info for reproducibility

```{r message =FALSE}
save(.Random.seed, file = "randomSeed4.1.txt")
sessionInfo() 
```

# Diameter - height 

```{r}
fitTH <- lmer(log10(TH) ~ log10(Dbh_a) * Stage + I(log10(Dbh_a)^2) + (1|Plot)) 
summary(fitTH)
anova(fitTH)
cleanedData$predictedTreeHeight<- predict(fitTH, newdata = cleanedData)

plot1 <- function(){
  plot(log10(Dbh_a), log10(TH), pch = as.numeric(Stage), xlim = c(0.5, 2), main = "Tree height", xlab = "Log10 DBH [cm]", ylab = "Log10 Height [m]")
  mtext("A", side = 2, adj=4, las=1, padj=-11, cex = 2)
  points(log10(Dbh_a), cleanedData$predictedTreeHeight, col = colorMap(Stage), cex = 0.2)
  legend("bottomright", legend = levels(Stage), pch = 1:3, col = colorMap(1:3), lwd = 1, bg = "white")
  

}
plot1()
```

#  Diameter - crown area

```{r}

fitCA <- lmer(log10(crownArea) ~ log10(Dbh_a) * Stage + I(log10(Dbh_a)^2) + (1|Plot)) 
summary(fitCA)
anova(fitCA)
cleanedData$predictedCrownArea<- predict(fitCA, newdata = cleanedData)

plot2 <- function(){
  plot(log10(Dbh_a), log10(crownArea), pch = as.numeric(Stage), xlim = c(0.5, 2), main = "Crown projection area", xlab = "Log10 DBH [cm]", ylab = "Log10 Area [m^2]")
  mtext("B", side = 2, adj=4, las=1, padj=-11, cex = 2)
  points(log10(Dbh_a), cleanedData$predictedCrownArea, col = colorMap(Stage), cex = 0.2)
  legend("bottomright", legend = levels(Stage), pch = 1:3, col = colorMap(1:3), lwd = 1, bg = "white")
  
  

}
plot2()
```

#  Diameter - crown height

```{r}


fitCH <- lmer(log10(crownHeight) ~ log10(Dbh_a) * Stage + I(log10(Dbh_a)^2) + (1|Plot)) 
summary(fitCH)
anova(fitCH)
cleanedData$predictedCrownHeight<- predict(fitCH, newdata = cleanedData)

plot3 <- function(){
  plot(log10(Dbh_a), log10(crownHeight), pch = as.numeric(Stage), xlim = c(0.5, 2), main = "Crown height", xlab = "Log10 DBH [cm]", ylab = "Log10 Height [m^2]")
 mtext("C", side = 2, adj=4, las=1, padj=-11, cex = 2)
  points(log10(Dbh_a), cleanedData$predictedCrownHeight, col = colorMap(Stage), cex = 0.2)
  legend("bottomright", legend = levels(Stage), pch = 1:3, col = colorMap(1:3), lwd = 1, bg = "white")
}
plot3()
```

#  Diameter - crown volume

```{r}


fitCV <- lmer(log10(crownVolume) ~ log10(Dbh_a) * Stage + I(log10(Dbh_a)^2) + (1|Plot)) 
summary(fitCV)
anova(fitCV)
cleanedData$predictedCrownVolume<- predict(fitCV, newdata = cleanedData)

plot4 <- function(){
  plot(log10(Dbh_a), log10(crownVolume), pch = as.numeric(Stage), xlim = c(0.5, 2), main = "Crown Volume", xlab = "Log10 DBH [cm]", ylab = "Log10 Volume [m^3]")
  mtext("D", side = 2, adj=4, las=1, padj=-11, cex = 2)
  points(log10(Dbh_a), cleanedData$predictedCrownVolume, col = colorMap(Stage), cex = 0.2)
  legend("bottomright", legend = levels(Stage), pch = 1:3, col = colorMap(1:3), lwd = 1, bg = "white")
}
plot4()
```

# cleaning up

```{r}

png("../results/paper/Allometries.png", width = 1000, height = 1000)
par(mfrow = c(2,2), cex = 1.3)
plot1()
plot2()
plot3()
plot4()
dev.off()
detach(cleanedData)


results.allometrie <- data.frame(fixef(fitTH), sqrt(diag(vcov(fitTH))), 
                                 fixef(fitCA), sqrt(diag(vcov(fitCA))), 
                                 fixef(fitCH), sqrt(diag(vcov(fitCH))),
                                 fixef(fitCV), sqrt(diag(vcov(fitCV))) )

colnames(results.allometrie) = c("Dia-Hei", "SE.H" ,"Dia-CA", "SE.CA" ,
                                 "Dia-CH", "SE.CH" ,"Dia-CV", "SE.CV" )


save.image(file = "../data/cleanedData2.RData")


```


