---
title: "Supplementary - Calculation of stand structure"
author: ""
date: "5 Aug 2014"
output: html_document
---

Report created with knitR. Source code see https://github.com/florianhartig/KhoaYaiSuccessionData

# Preparing workspace

```{r message =FALSE}
rm(list=ls(all=TRUE))
source("01-packages.R", print.eval =F)
load(file = "../data/cleanedData2.RData")
attach(cleanedData)
stagesPerPlot <- as.factor(c("Establishment", "Establishment", "Establishment", "Exclusion", "Exclusion","Exclusion", "Old-growth", "Old-growth"))
```

### Session info for reproducibility

```{r message =FALSE}
save(.Random.seed, file = "randomSeed.4.3.txt")
sessionInfo() 
```


# Differences in stem number and lean


```{r, fig.height=15, fig.width=15}

  png("../results/paper/standVariables.png", width = 800, height = 700)

  par(mfrow=c(2,2), oma = c(0,0,0,0), cex = 1.3)

  Gcol = rev(gray.colors(3))

  # STEM DENSITY #


  density <- table(Stage, Plot)
  barplot(density, las = 1, xlab = "Stem number [/0.48 ha]", space = 1, horiz = T, main = "Stem number", col = Gcol, legend = levels(Stage) , args.legend =list(x=2000, y = 19, fill = Gcol, bg = NULL, bty = "n"))



  mtext("A", side = 2, adj=4, las=1, padj=-9, cex = 1.5)

  # Basal Area #
  
  boot.BA <- function(vec,f)return(sum(pi*vec[f]^2 / 10000, na.rm = T )) 
  result <- foreach(i=1:8) %do% boot(Dbh_a[as.numeric(Plot) == i], boot.BA, 1000)
  bestEstimate <- unlist(foreach(i=1:8) %do% result[[i]]$t0)
  confintervals <- foreach(i=1:8) %do% boot.ci(result[[i]], type = "basic")
  CI <- matrix(unlist(foreach(i=1:8) %do% confintervals[[i]]$basic[1,4:5]), nrow = 2, byrow = F)

  barplot2(bestEstimate, ci.l = CI[1,] ,ci.u = CI[2,], plot.ci = T, horiz = T, space = 1, main = "Basal Area", xlab = "Basal area [m^2/0.48 ha]", col = Gcol[stagesPerPlot], names.arg = colnames(density), las =1 )

 mtext("B", side = 2, adj=4, las=1, padj=-9, cex = 1.5)

  # Crown Area #
  
  boot.sum <- function(vec,f)return(sum(vec[f], na.rm = T )) 
  result <- foreach(i=1:8) %do% boot(predictedCrownArea[as.numeric(Plot) == i], boot.sum, 1000)
  bestEstimate <- unlist(foreach(i=1:8) %do% result[[i]]$t0)
  confintervals <- foreach(i=1:8) %do% boot.ci(result[[i]], type = "basic")
  CI <- matrix(unlist(foreach(i=1:8) %do% confintervals[[i]]$basic[1,4:5]), nrow = 2, byrow = F)

  barplot2(bestEstimate, ci.l = CI[1,] ,ci.u = CI[2,], plot.ci = T, horiz = T, space = 1, main = "Crown projection area", xlab = "Crown projection area [m^2/0.48 ha]", col = Gcol[stagesPerPlot], names.arg = colnames(density), las =1 )

 mtext("C", side = 2, adj=4, las=1, padj=-9, cex = 1.5)

  # LEAN #
  
  boot.median <- function(vec,f)return(median(vec[f], na.rm = T )) 
  leanPerPlot <- foreach(i=1:8) %do% boot(inclination[as.numeric(Plot) == i & Dbh_a<7], boot.median, 1000)
  bestEstimateLean <- unlist(foreach(i=1:8) %do% leanPerPlot[[i]]$t0)
  confintervals <- foreach(i=1:8) %do% boot.ci(leanPerPlot[[i]], type = "basic")
  CI <- matrix(unlist(foreach(i=1:8) %do% confintervals[[i]]$basic[1,4:5]), nrow = 2, byrow = F)

  barplot2(bestEstimateLean, ci.l = CI[1,] ,ci.u = CI[2,], plot.ci = T, horiz = T, space = 1, main = "Lean [dbh < 7]", xlab = "Average inclination [degrees]", col = Gcol[stagesPerPlot], names.arg = colnames(density), las =1 )

 mtext("D", side = 2, adj=4, las=1, padj=-9, cex = 1.5)

  
dev.off()


img <- readPNG("../results/paper/standVariables.png")
grid::grid.raster(img)


#differences NS
fitI <- lmer(inclination ~ Stage + (1|Plot), data = cleanedData[cleanedData$Dbh_a<7,]) 
summary(fitI)
anova(fitI)



```







# checks whether there is some difference in the spatial pattern of tree species in the different plots

```{r, fig.width=20, fig.height=20, cache=T}

plots <- unique(cleanedData$Plot)

png("../results/paper/spatialPatterns-plots.png", width = 1000, height = 1000)

par(mfrow=c(4,4))

for (i in 1:length(plots)){
  
  selectedData <- cleanedData[cleanedData$Plot == plots[i] & !is.na(cleanedData$Dbh_a) & cleanedData$Dbh_a > 5,]
  attach(selectedData)
  pattern <- ppp(X , Y, window=owin(c(0,ceiling(max(X))),c(0,ceiling(max(Y)))))  
  
  fit <- kppm(pattern, ~1, "Thomas")
  summary(fit)
  
  plot(pattern, cex = 0.3, main = paste(Plot[1], Stage[2]))
  
  plot(envelope(fit, fun = "Gest"), main = paste(Plot[1], Stage[2]))
  
  detach(selectedData)
}

dev.off()

img <- readPNG("../results/paper/spatialPatterns-plots.png")
grid::grid.raster(img)


```



# cleaning up 

```{r}

detach(cleanedData)

```


