---
title: "Supplementary - Calculation of community composition"
author: ''
date: "5 Aug 2014"
output:
  html_document: default
  pdf_document: default
---

Report created with knitR. Source code see https://github.com/florianhartig/KhoaYaiSuccessionData

# Preparing workspace

```{r message =FALSE}
rm(list=ls(all=TRUE))
source("01-packages.R", print.eval =F)
load(file = "../data/cleanedData2.RData")
attach(cleanedData)
stagesPerPlot <- as.factor(c("Establishment", "Establishment", "Establishment", "Exclusion", "Exclusion","Exclusion", "Old-growth", "Old-growth"))
```

### Session info for reproducibility

```{r message =FALSE}
save(.Random.seed, file = "randomSeed4.4.txt")
sessionInfo() 
```


# Diversity

```{r}

png("../results/paper/DiversityIndices.png", width = 500, height = 500)
par(cex = 1.4)

totalrichness = length(unique(as.numeric(Species)))
simpson <- foreach(i=1:8) %do% diversity(table(Species[as.numeric(Plot) == i]), index = "invsimpson")
richness <- foreach(i=1:8) %do% (length(unique(Species[as.numeric(Plot) == i])) )

tmp <- cbind(unlist(simpson), unlist(richness))
Gcol = rev(gray.colors(3))
bp <- barplot(tmp, beside=T, names = c("Inv-Simpson", "Richness"), las = 1, col = Gcol[stagesPerPlot], ylim = c(0,100))
legend(1,100, legend = unique(stagesPerPlot), col = Gcol, pch = 15, bg=NULL, bty = "n")
text(bp-0.4, tmp + 2, rep(levels(Plot),2),cex=0.8,pos=4, srt = 90) 


dev.off()

# displaying the result in R
img <- readPNG("../results/paper/DiversityIndices.png")
grid::grid.raster(img)

```

# Community similarity

```{r}

# Checks for similarity in the community matrix and then clusters the plots according to that


# create community matrix per plot
communityMatrix <- table(Plot, Species)
# calculate Bray-Curtis distance among samples
comm.bc.dist <- vegdist(communityMatrix, method = "bray")
# cluster communities using average-linkage algorithm
comm.bc.clust <- hclust(comm.bc.dist, method = "average")
# plot cluster diagram

levels(cleanedData$Stage)
unique(cleanedData$Plot)

stagePlot = foreach(i=1:length(comm.bc.clust$labels))  %do% as.character(cleanedData$Stage[comm.bc.clust$labels[i] == cleanedData$Plot][1])

names = paste(comm.bc.clust$labels, " (", unlist(stagePlot), ")", sep = "")

```

Standard hierarchical cluster plot

```{r}
plot(comm.bc.clust)
```

As unrooted phylogeny, used for the paper

```{r}
png("../results/paper/CommunitySimilarity.png", width = 500, height = 500)
par(cex = 1.3)
plot(comm.bc.clust)

Gcol = c("black", "chartreuse4", "darkorange")
Gcol = rev(c("black", "darkgrey", "lightgrey"))

plot(as.phylo(comm.bc.clust, directed = F), main = "Bray-Curtis community similarity", type = "unrooted", tip.color = Gcol[stagesPerPlot])


axis(side = 1, at = seq(0,1,0.2)-0.1, labels =  seq(0,1,0.2), xlim = c(0,1))

dev.off()

# displaying the result in R
img <- readPNG("../results/paper/CommunitySimilarity.png")
grid::grid.raster(img)


```

# Similarity in size classes 

Analysis not presented in the paper 


```{r}

# Checks for similarity in the community matrix and then clusters the plots according to that

#png("../results/paper/CommunitySimilarity10Split.png", width = 800, height = 400)
par(cex = 1.2, mfrow = c(1,2))

sel <- Dbh_a < 10

# create community matrix per plot
communityMatrix <- table(Plot[sel], Species[sel])
# calculate Bray-Curtis distance among samples
comm.bc.dist <- vegdist(communityMatrix, method = "bray")
# cluster communities using average-linkage algorithm
comm.bc.clust <- hclust(comm.bc.dist, method = "average")
# plot cluster diagram

levels(cleanedData$Stage)
unique(cleanedData$Plot)

stagePlot = foreach(i=1:length(comm.bc.clust$labels))  %do% as.character(cleanedData$Stage[comm.bc.clust$labels[i] == cleanedData$Plot][1])

names = paste(comm.bc.clust$labels, " (", unlist(stagePlot), ")", sep = "")

plot(comm.bc.clust, ylab = "Bray-Curtis dissimilarity", main = "Community similarity", xlab = "", labels = names)

sel <- Dbh_a > 10

# create community matrix per plot
communityMatrix <- table(Plot[sel], Species[sel])
# calculate Bray-Curtis distance among samples
comm.bc.dist <- vegdist(communityMatrix, method = "bray")
# cluster communities using average-linkage algorithm
comm.bc.clust <- hclust(comm.bc.dist, method = "average")
# plot cluster diagram

levels(cleanedData$Stage)
unique(cleanedData$Plot)

stagePlot = foreach(i=1:length(comm.bc.clust$labels))  %do% as.character(cleanedData$Stage[comm.bc.clust$labels[i] == cleanedData$Plot][1])

names = paste(comm.bc.clust$labels, " (", unlist(stagePlot), ")", sep = "")

plot(comm.bc.clust, ylab = "Bray-Curtis dissimilarity", main = "Community similarity", xlab = "", labels = names)

#dev.off()

# displaying the result in R
#img <- readPNG("../results/paper/CommunitySimilarity10Split.png")
#grid::grid.raster(img)

detach(cleanedData)
```

